#!/bin/sh
IPT="iptables -w 5"
SET="vpn_domains"
TPORT=9999
IFACE="__IFACE__"

$IPT -t nat -D PREROUTING -i $IFACE -p tcp -m set --match-set $SET dst --dport 443 \
  -j REDIRECT --to-port $TPORT 2>/dev/null

$IPT -t nat -A PREROUTING -i $IFACE -p tcp -m set --match-set $SET dst --dport 443 \
  -j REDIRECT --to-port $TPORT