name: Build RayGate IPK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install opkg-utils
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential python3
          git clone https://git.yoctoproject.org/opkg-utils
          cd opkg-utils
          make
          sudo make install
          opkg-build --version

      - name: Prepare dist directory
        run: |
          mkdir -p dist
          cp -r raygate/* dist/ || true

      - name: Build IPK package
        run: |
          cd dist
          mkdir -p ../output
          opkg-build -o root -g root . ../output

      - name: Upload IPK artifact
        uses: actions/upload-artifact@v4
        with:
          name: raygate-ipk
          path: output/*.ipk
