name: Build RayGate IPK

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version from control
        id: get_version
        run: echo "VERSION=$(grep -m1 '^Version:' raygate/CONTROL/control | awk '{print $2}')" >> $GITHUB_ENV

      - name: Prepare build environment
        run: |
          mkdir -p build/raygate/CONTROL
          mkdir -p build/raygate/opt

      - name: Copy files
        run: |
          # CONTROL
          cp raygate/CONTROL/control build/raygate/CONTROL/
          cp raygate/CONTROL/postinst build/raygate/CONTROL/
          chmod 755 build/raygate/CONTROL/postinst

          # OPT
          cp -r raygate/opt/* build/raygate/opt/

      - name: Make gzip IPK (nfqws-style)
        run: |
          cd build/raygate
          tar -czf ../../raygate_${VERSION}_all.ipk CONTROL opt
  
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: raygate_${{ env.VERSION }}_all.ipk
          path: raygate_${{ env.VERSION }}_all.ipk

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: raygate_${{ env.VERSION }}_all.ipk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
