name: Build RayGate IPK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install opkg-utils (contains opkg-build)
        run: |
          sudo apt-get update
          sudo apt-get install -y opkg-utils

      - name: Ensure executable bits
        run: |
          chmod +x raygate/CONTROL/postinst || true
          chmod +x raygate/opt/etc/init.d/S99raygate || true
          chmod +x raygate/opt/bin/raygate/raygate_add.sh || true
          chmod +x raygate/opt/bin/raygate/rayweb/rayweb.py || true

      - name: Build IPK
        run: |
          opkg-build raygate
          ls -l *.ipk

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: raygate-ipk
          path: ./*.ipk
