name: Build & Publish RayGate IPK

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # === 1. Клонируем код ===
      - name: Checkout repository
        uses: actions/checkout@v4

      # === 2. Определяем версию ===
      - name: Set version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            VERSION="${GITHUB_REF##*/}"   # refs/tags/v1.0.0 → v1.0.0
            VERSION="${VERSION#v}"        # v1.0.0 → 1.0.0
          else
            VERSION="$(grep -m1 -E '^Version:' raygate/CONTROL/control | awk '{print $2}')"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

          # Если тег — правим control
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            sed -i "s/^Version:.*/Version: $VERSION/" raygate/CONTROL/control
          fi

      # === 3. Нормализация control и postinst ===
      - name: Normalize control and postinst
        run: |
          sed -i '1s/^\xEF\xBB\xBF//' raygate/CONTROL/control
          sed -i 's/\r//g' raygate/CONTROL/control
          sed -i '1s/^\xEF\xBB\xBF//' raygate/CONTROL/postinst
          sed -i 's/\r//g' raygate/CONTROL/postinst
          chmod 755 raygate/CONTROL/postinst
          chmod 755 raygate/CONTROL/prerm

      # === 4. Подготовка директорий ===
      - name: Prepare build directories
        run: |
          rm -rf build
          mkdir -p build/CONTROL build/data

      # === 5. Копирование control и данных ===
      - name: Copy files into control and data
        run: |
          cp raygate/CONTROL/control build/CONTROL/
          cp raygate/CONTROL/postinst build/CONTROL/
          cp raygate/CONTROL/prerm build/CONTROL/
          cp -r raygate/opt/ build/data/

      # === 6. Создание control.tar.gz и data.tar.gz ===
      - name: Build control.tar.gz and data.tar.gz
        run: |
          GZIP=-n tar --numeric-owner --group=0 --owner=0 -C build/CONTROL -czf build/control.tar.gz .
          GZIP=-n tar --numeric-owner --group=0 --owner=0 -C build/data    -czf build/data.tar.gz .

      # === 7. Создание debian-binary ===
      - name: Create debian-binary
        run: printf '2.0\n' > build/debian-binary

      # === 8. Сборка .ipk ===
      - name: Assemble .ipk
        run: |
          mkdir pkgroot
          cp build/debian-binary pkgroot/
          cp build/control.tar.gz pkgroot/
          cp build/data.tar.gz pkgroot/
          GZIP=-n tar -C pkgroot -czf raygate_${VERSION}_all.ipk .

      # === 9. Если это main — билд dev и заливаем как артефакт ===
      - name: Upload artifact (dev build)
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: raygate_${{ env.VERSION }}_dev.ipk
          path: raygate_${{ env.VERSION }}_all.ipk

      # === 10. Если это тег — публикем релиз и opkg feed ===
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: raygate_${{ env.VERSION }}_all.ipk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout gh-pages
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Install opkg-utils
        run: |
            git clone https://git.yoctoproject.org/opkg-utils
            sudo install -m 755 opkg-utils/opkg-make-index /usr/local/bin/opkg-make-index
  
      - name: Update /all feed
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          mkdir -p gh-pages/all
          cp raygate_${VERSION}_all.ipk gh-pages/all/
          cd gh-pages/all
          opkg-make-index . > Packages
          gzip -k Packages

      - name: Commit & push gh-pages
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add all/
          git commit -m "Update feed to v${VERSION}"
          git push origin gh-pages
