name: Build RayGate IPK

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version from control
        id: get_version
        run: echo "VERSION=$(grep -m1 '^Version:' CONTROL/control | awk '{print $2}')" >> $GITHUB_ENV

      - name: Prepare build directories
        run: |
          mkdir -p build/pkg
          mkdir -p build/control
          mkdir -p build/data

      - name: Copy CONTROL files
        run: |
          cp raygate/CONTROL/control build/control/
          cp raygate/CONTROL/postinst build/control/
          chmod 755 build/control/postinst

      - name: Copy data files
        run: |
          cp -r raygate/opt build/data/

      - name: Create debian-binary
        run: echo "2.0" > build/pkg/debian-binary

      - name: Create control.tar.gz
        run: |
          cd build/control
          tar --format=gnu -czf ../pkg/control.tar.gz *

      - name: Create data.tar.gz
        run: |
          cd build/data
          tar --format=gnu -czf ../pkg/data.tar.gz *

      - name: Build final IPK
        run: |
          cd build/pkg
          ar r "../../raygate_${VERSION}_all.ipk" debian-binary control.tar.gz data.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: raygate_${{ env.VERSION }}_all.ipk
          path: raygate_${{ env.VERSION }}_all.ipk
