name: Build RayGate IPK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install opkg-utils
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential python3
          git clone https://git.yoctoproject.org/opkg-utils
          cd opkg-utils
          make
          sudo make install
          opkg-build 2>/dev/null || true

      - name: Prepare dist directory
        shell: bash
        run: |
          set -eux
          rm -rf dist output
          mkdir -p dist output
          cp -a raygate/. dist/

      - name: Fix line endings & permissions inside dist
        shell: bash
        run: |
          set -eux
          sed -i 's/\r$//' dist/CONTROL/control               || true
          sed -i 's/\r$//' dist/CONTROL/postinst              || true
          sed -i 's/\r$//' dist/opt/etc/init.d/S99raygate     || true
          sed -i 's/\r$//' dist/opt/bin/raygate/raygate_add.sh || true
          sed -i 's/\r$//' dist/opt/bin/raygate/rayweb/rayweb.py || true
          sed -i 's/\r$//' dist/opt/etc/xray/config.json      || true

          chmod 0755 dist/CONTROL/postinst
          chmod 0755 dist/opt/etc/init.d/S99raygate
          chmod 0755 dist/opt/bin/raygate/raygate_add.sh

          test -f dist/CONTROL/control
          test -f dist/CONTROL/postinst
          test -f dist/opt/etc/init.d/S99raygate

      - name: Build IPK package
        shell: bash
        run: |
          set -eux
          PKGDIR="$(pwd)/dist"
          DEST="$(pwd)/output"
          opkg-build -o root -g root "$PKGDIR" "$DEST"
          echo "Built packages:"
          ls -l "$DEST"

      - name: Upload IPK artifact
        uses: actions/upload-artifact@v4
        with:
          name: raygate-ipk
          path: output/*.ipk

      - name: Prepare opkg feed (copy + index)
        shell: bash
        run: |
          set -eux
          mkdir -p opkg/all
          cp -f output/*.ipk opkg/all/
          opkg-make-index opkg/all > opkg/all/Packages
          gzip -f opkg/all/Packages
          ls -l opkg/all

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: opkg

  deploy: 
    needs: build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
