name: Build RayGate IPK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install opkg-utils
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential python3
          git clone https://git.yoctoproject.org/opkg-utils
          cd opkg-utils
          make
          sudo make install
          opkg-build --version

      - name: Prepare dist directory
        run: |
          rm -rf dist output
          mkdir -p dist
          cp -r raygate/* dist/ || true

      - name: Fix line endings & permissions inside dist
        shell: bash
        run: |
          set -eux
          # CRLF -> LF (на всякий случай)
          sed -i 's/\r$//' dist/CONTROL/control        || true
          sed -i 's/\r$//' dist/CONTROL/postinst       || true
          sed -i 's/\r$//' dist/opt/etc/init.d/S99raygate || true
          sed -i 's/\r$//' dist/opt/bin/raygate/raygate_add.sh || true
          sed -i 's/\r$//' dist/opt/bin/raygate/rayweb/rayweb.py || true
          sed -i 's/\r$//' dist/opt/etc/xray/config.json || true

          chmod 0755 dist/CONTROL/postinst
          chmod 0755 dist/opt/etc/init.d/S99raygate
          chmod 0755 dist/opt/bin/raygate/raygate_add.sh

      - name: Build IPK package
        run: |
          mkdir -p output
          cd dist
          opkg-build -o root -g root . ../output
          echo "Built packages:"
          ls -l ../output

      - name: Upload IPK artifact
        uses: actions/upload-artifact@v4
        with:
          name: raygate-ipk
          path: output/*.ipk
