name: Build RayGate IPK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install minimal build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y git file tar xz-utils

      - name: Install opkg-build (from opkg-utils)
        run: |
          git clone https://git.openwrt.org/project/opkg-utils.git /tmp/opkg-utils
          sudo install -m 0755 /tmp/opkg-utils/opkg-build /usr/local/bin/opkg-build
          opkg-build --help | head -n 3

      - name: Normalize line endings (CRLF -> LF)
        run: |
          sed -i 's/\r$//' raygate/CONTROL/* || true
          find raygate -type f -name "*.sh" -exec sed -i 's/\r$//' {} \; || true
          chmod +x raygate/CONTROL/postinst || true
          chmod +x raygate/opt/etc/init.d/S99raygate || true
          chmod +x raygate/opt/bin/raygate/raygate_add.sh || true
          chmod +x raygate/opt/bin/raygate/rayweb/rayweb.py || true

      - name: Build IPK
        run: |
          opkg-build -o root -g root raygate
          ls -l *.ipk

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: raygate-ipk
          path: ./*.ipk
