name: Build RayGate IPK

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            VERSION="${GITHUB_REF#refs/tags/v}"
          else
            VERSION="dev"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Building RayGate version: $VERSION"

      - name: Prepare build environment
        run: |
          mkdir -p build/raygate/CONTROL
          mkdir -p build/raygate/opt

      - name: Copy files
        run: |
          # CONTROL
          cp raygate/CONTROL/control build/raygate/CONTROL/
          cp raygate/CONTROL/postinst build/raygate/CONTROL/
          chmod 755 build/raygate/CONTROL/postinst

          # OPT
          cp -r opt/* build/raygate/opt/ || echo "No opt files found"

      - name: Make gzip IPK (nfqws-style)
        run: |
          cd build/raygate
          tar -czf ../../raygate_${VERSION}_all.ipk CONTROL opt
  
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: raygate_${{ env.VERSION }}_all.ipk
          path: raygate_${{ env.VERSION }}_all.ipk

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: raygate_${{ env.VERSION }}_all.ipk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
