name: Build RayGate IPK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    container:
      image: openwrt/sdk:x86_64
      options: --user root

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare package directory
        run: |
          mkdir -p /builder/raygate
          cp -r raygate/* /builder/raygate/

      - name: Build IPK
        working-directory: /builder
        run: |
          opkg-build raygate

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: raygate-ipk
          path: /builder/raygate_*.ipk
