name: Build RayGate IPK

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Normalize control and postinst
        run: |
          # Убираем BOM/CRLF
          sed -i '1s/^\xEF\xBB\xBF//' raygate/CONTROL/control
          sed -i 's/\r//g' raygate/CONTROL/control
          sed -i '1s/^\xEF\xBB\xBF//' raygate/CONTROL/postinst
          sed -i 's/\r//g' raygate/CONTROL/postinst
          sed -i 's/^[[:space:]]*\(Package\|Version\|Architecture\|Maintainer\|Section\|Priority\|Depends\|Description\)/\1/' raygate/CONTROL/control
          # sed -i 's/^Architecture:.*/Architecture: aarch64-3.10/' raygate/CONTROL/control
          chmod 755 raygate/CONTROL/postinst

      - name: Extract version from control
        id: get_version
        run: |
          VERSION=$(grep -m1 -E '^Version:' raygate/CONTROL/control | awk '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Prepare build directories
        run: |
          rm -rf build
          mkdir -p build/CONTROL build/data

      - name: Copy files into control and data
        run: |
          cp raygate/CONTROL/control build/CONTROL/
          cp raygate/CONTROL/postinst build/CONTROL/
          cp -r raygate/opt/ build/data/

      - name: Build control.tar.gz and data.tar.gz
        run: |
          GZIP=-n tar --numeric-owner --group=0 --owner=0 -C build/CONTROL -czf build/control.tar.gz .
          GZIP=-n tar --numeric-owner --group=0 --owner=0 -C build/data    -czf build/data.tar.gz .

      - name: Create debian-binary
        run: printf '2.0\n' > build/debian-binary

      - name: Assemble .ipk (OpenWrt style)
        run: |
          mkdir pkgroot
          cp build/debian-binary pkgroot/
          cp build/control.tar.gz pkgroot/
          cp build/data.tar.gz pkgroot/
          GZIP=-n tar -C pkgroot -czf raygate_${VERSION}_all.ipk .

      - name: Copy dev build
        run: cp raygate_${VERSION}_all.ipk raygate_${VERSION}_dev.ipk

      - name: Upload artifact (dev build)
        uses: actions/upload-artifact@v4
        with:
          name: raygate_${{ env.VERSION }}_dev.ipk
          path: raygate_${{ env.VERSION }}_dev.ipk

      - name: Create Release (only on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: raygate_${{ env.VERSION }}_all.ipk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
